### ISSUE TITLE
https://juliamolsim.org/   redirects to DFTK

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/JuliaMolSim.github.io#13]
The web-address `https://juliamolsim.org/` is apparently linked to the DFTK repository instead of the JuliaMolSim Landing page.

**Comment by mfherbst** [comment]
Really ... this is not intentional and funnily I cannot reproduce it on my end.

**Comment by cortner** [comment]
maybe some problem in my browser cache? It happens on both of the browsers I have on my laptop and on my phone. Also - interestingly, both browsers first give me a warning that the site in unsecure, maybe because it redirects?

**Comment by rkurchin** [comment]
A bunch of the workshop speakers/participants have been having issues resolving that URL and getting various warnings, but the `juliamolsim.github.io` one works fine. I've only been able to reproduce sporadically on my phone so also hard to figure out.

**Comment by cortner** [comment]
> but the juliamolsim.github.io one works fine

yes, I can confirm that.

**Comment by mfherbst** [comment]
Is this still an issue by the way. I recently changed something here.
